language: objective-c
osx_image: xcode8.1
cache:
  directories:
  - Carthage
install:
- bin/bootstrap-if-needed
script:
- xcodebuild -project SpechtLite.xcodeproj -scheme "SpechtLite" build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
before_deploy:
- openssl aes-256-cbc -K $encrypted_f333a4d93d89_key -iv $encrypted_f333a4d93d89_iv -in secret.tar.enc -out cert/secret.tar -d
- tar xvf cert/secret.tar
- security create-keychain -p mysecretpassword build.keychain
- security default-keychain -s build.keychain
- security unlock-keychain -p mysecretpassword build.keychain
- security import cert/MacDistribution.p12 -k build.keychain -T /usr/bin/codesign
  -P ""
# unshallow repository
- "[ -f $(git rev-parse --git-dir)/shallow ] && git fetch --unshallow"
- gem install gym github-markup redcarpet --no-ri --no-rdoc
- gym
- ditto -c -k --sequesterRsrc --keepParent SpechtLite.app SpechtLite.zip
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IGPLdiy+AuIA3fjZA2d7BM3qiu0cvIGPhRaU9gnPLjXLKggB2vRFfZUHjB3TSvVJ1yX5Pf5xO5iCmJvlfDF2QHf0rTQKwsGBX+Q7iloLtaw+mYYpCwnpVR8IVDmEtDvw59p/YOsBhh490XckCOs1ihA9vZPGmuGz+Ap1vFMQNadRnO1hfBgxGJ9Jg6QptM+O5QP83DgEaZcJbin7mZKftWFAQf5vJgtRZHEY2NTfoejLj8P6hesPEeO5UDfwQYl0z4nrDlC1jK5Tyh6d9IRYxyKtuzl8kydk//KncsMmX2quWUl81urRrt8NEGh/niHzY1FGfvjm3W0vIhK3ELoDolZlKHpB02fTfkdleyOozQSGN+1pKT2aHuo1HkU8J9YTY2tKhu0qIocHwdTvDRS9gWbhmbrBg9MC3tmfKNpp8japH1I8W2Rhk1wQPKNLwpk/XUcB73/NV84uGTTVLNiV+AEFtxRzNf4hx/fQT8FvkjV5zSyQhPuQXhjv0Zqpx+CA/SIQZbrPwqmPyEA183ZTyyLD0Uwm+3pix8TPU4z7+kOhh/ydXoRxkRxqHX98eXwSp5e8Y1+Xuv7udLsQ89PqjtKYMpjRMYBkZxvQSL02etJCy+EgknHsxwbbfaQ6IMXQeDtxk97WKBgy7O461Bb5kswNuDPztICkVX3H849MFSc=
  file: SpechtLite.zip
  on:
    repo: zhuhaow/SpechtLite
    tags: true
after_deploy:
- bin/publish_appcast
